<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>cb2ee934de8aab15a22fe2d</sessionid><type>desync</type><sku>ea.maxis.sims4.15.mac</sku><createtime>2017-12-02 14:52:35</createtime><buildsignature>Local.Unknown.Unknown.1.36.104.1220-1.200.000.311.Release</buildsignature><categoryid>resolver.py:101</categoryid><desyncid>cb2ee934de8aab15a22fe2d</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 195, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 203, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 434, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 4003, in do_transition_single&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3959, in _create_transition_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3852, in run_super_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3637, in run_direct_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 598, in run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4738, in perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5586, in perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1457, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\__init__.py", line 54, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6484, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 251, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 360, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 358, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 607, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal_multi_sim.py", line 133, in _run_goal_completion_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 734, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 101, in __call__&#13;&#10;AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>cb2ee934de8aab15a22fe2d</sessionid><type>desync</type><sku>ea.maxis.sims4.15.mac</sku><createtime>2017-12-02 14:52:40</createtime><buildsignature>Local.Unknown.Unknown.1.36.104.1220-1.200.000.311.Release</buildsignature><categoryid>resolver.py:101</categoryid><desyncid>cb2ee934de8aab15a22fe2d</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 195, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 203, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 434, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 4003, in do_transition_single&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3959, in _create_transition_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3852, in run_super_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3637, in run_direct_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 598, in run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4738, in perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5586, in perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1457, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\__init__.py", line 54, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6484, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 251, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 360, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 358, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 607, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal_multi_sim.py", line 133, in _run_goal_completion_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 734, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 101, in __call__&#13;&#10;AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>cb2ee934de8aab15a22fe2d</sessionid><type>desync</type><sku>ea.maxis.sims4.15.mac</sku><createtime>2017-12-02 14:52:45</createtime><buildsignature>Local.Unknown.Unknown.1.36.104.1220-1.200.000.311.Release</buildsignature><categoryid>resolver.py:101</categoryid><desyncid>cb2ee934de8aab15a22fe2d</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 195, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 203, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 434, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 3366, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 740, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1615, in run_transitions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3852, in run_super_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 3637, in run_direct_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 598, in run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4738, in perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5586, in perform_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1457, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\__init__.py", line 54, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6484, in _trigger_interaction_start_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 251, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 360, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 358, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 607, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal_multi_sim.py", line 133, in _run_goal_completion_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 734, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 101, in __call__&#13;&#10;AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>cb2ee934de8aab15a22fe2d</sessionid><type>desync</type><sku>ea.maxis.sims4.15.mac</sku><createtime>2017-12-02 14:52:49</createtime><buildsignature>Local.Unknown.Unknown.1.36.104.1220-1.200.000.311.Release</buildsignature><categoryid>resolver.py:101</categoryid><desyncid>cb2ee934de8aab15a22fe2d</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 195, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 203, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 434, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 912, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 313, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1111, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4531, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1419, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4543, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6839, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\__init__.py", line 62, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5921, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 251, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 360, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 358, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 607, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal_multi_sim.py", line 133, in _run_goal_completion_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 734, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 101, in __call__&#13;&#10;AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>cb2ee934de8aab15a22fe2d</sessionid><type>desync</type><sku>ea.maxis.sims4.15.mac</sku><createtime>2017-12-02 14:52:57</createtime><buildsignature>Local.Unknown.Unknown.1.36.104.1220-1.200.000.311.Release</buildsignature><categoryid>resolver.py:101</categoryid><desyncid>cb2ee934de8aab15a22fe2d</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 195, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 203, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 434, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 3366, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 768, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 912, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 313, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1111, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4531, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1419, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4543, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6839, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\__init__.py", line 62, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5921, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 251, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 360, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 358, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 607, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal_multi_sim.py", line 133, in _run_goal_completion_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 734, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 101, in __call__&#13;&#10;AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs'&#13;&#10;</desyncdata></report>
<report><version>2</version><sessionid>cb2ee934de8aab15a22fe2d</sessionid><type>desync</type><sku>ea.maxis.sims4.15.mac</sku><createtime>2017-12-02 14:52:57</createtime><buildsignature>Local.Unknown.Unknown.1.36.104.1220-1.200.000.311.Release</buildsignature><categoryid>resolver.py:101</categoryid><desyncid>cb2ee934de8aab15a22fe2d</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 195, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 203, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 434, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 3366, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 661, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 912, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 313, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1111, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4531, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1419, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4543, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6839, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\__init__.py", line 62, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5921, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 251, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 360, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 358, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 607, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal_multi_sim.py", line 133, in _run_goal_completion_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 734, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 101, in __call__&#13;&#10;AttributeError: 'MultipleSimInteractionOfInterest' object has no attribute 'expected_kwargs'&#13;&#10;</desyncdata></report>
</root>